### ISSUE TITLE
organization recognition search only searches the start of name

### ISSUE THREAD

**Issue by dryice** [rewardz/Feeds#127] opened 2023-04-04 06:04 UTC
code is [here](https://github.com/rewardz/Feeds/blob/master/feeds/views.py#L1106)

The issue is for name like "WOO HUI LIN (HU HUILIN" (user ID  1036612 on Cerra SG), searching "woo" works, but searching "Hui" doesn't. @bryan got a report from McDonalds.

Not sure if that's a requirements from other clients or we can change.

**Comment by suryaiiit** [comment] 2023-04-04 16:20
I think the issue is because we are filtering the user name by starts with at [code](https://github.com/rewardz/Feeds/blob/master/feeds/views.py#L1118) instead of contains

**Comment by Biplabsing** [comment] 2023-04-11 08:26
@yatishTrootech @VipinRewardz  as we discussed we have some issue From FE side ,so yustar is working on it .it will be Better that if we clear this from FE side first  then close this card.
Note - BE side from Api response its working fine 
CC @suryaiiit @SteffiVinod5

**Comment by suryaiiit** [comment] 2023-04-11 08:29
@Biplabsing the issue is with the API response, if the API response is fine then we can close this.

**Closed** 2023-04-11 09:21 UTC

**Comment by Biplabsing** [comment] 2023-04-12 12:13
Working fine on skordev
@suryaiiit
